apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ip-geolocation-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arian24b/General_SRE_Challenge_K8S_Ansible
    targetRevision: HEAD
    path: application/helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
