apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: application
spec:
  selector:
    postgres-operator.crunchydata.com/cluster: postgres-cluster
    postgres-operator.crunchydata.com/role: master
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
