apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: application
type: Opaque
data:
  # Base64 encoded values
  username: YXBwdXNlcg== # appuser
  password: cGFzc3dvcmQ= # password
  database: cG9zdGdyZXM= # postgres
